In [1]:
import pandas as pd 
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import joblib

In [2]:
import pandas as pd
import numpy as np 
df= pd.read_csv("../cicids2017_cleaned.csv")
df.columns = df.columns.str.strip()
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)
print("Shape of the dataset:",df.shape)
print("Colums in dataset",df.columns.tolist())
label_col = "Label" if "Label" in df.columns else "Attack Type"
print(f"\n Class distribution in '{label_col}':\n",df[label_col].value_counts())

C:\Users\sahis\AppData\Local\Temp\ipykernel_11848\2572032113.py:3: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv("../cicids2017_cleaned.csv")


Shape of the dataset: (2520751, 53)
Colums in dataset ['Destination Port', 'Flow Duration', 'Total Fwd Packets', 'Total Length of Fwd Packets', 'Fwd Packet Length Max', 'Fwd Packet Length Min', 'Fwd Packet Length Mean', 'Fwd Packet Length Std', 'Bwd Packet Length Max', 'Bwd Packet Length Min', 'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd Header Length', 'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s', 'Min Packet Length', 'Max Packet Length', 'Packet Length Mean', 'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count', 'PSH Flag Count', 'ACK Flag Count', 'Average Packet Size', 'Subflow Fwd Bytes', 'Init_Win_bytes_forward', 'Init_Win_bytes_backward', 'act_data_pkt_fwd', 'min_seg_size_forward', 'Active Mean', 'A

In [3]:
label_column = 'Attack Type'
X=df.drop(columns=[label_column])
y=df[label_column]

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

In [5]:
print ("y_test distribution:\n", y_test.value_counts())

y_test distribution:
 Attack Type
Normal Traffic    419012
DoS                38749
DDoS               25603
Port Scanning      18139
Brute Force         1830
Web Attacks          429
Bots                 389
Name: count, dtype: int64


In [6]:
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [7]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
y_pred = model.predict(X_test)
print("Accuracy:",accuracy_score(y_test, y_pred))
print("\nConfusion matrix:\n",confusion_matrix(y_test, y_pred))
print("\nClassification_report:\n", classification_report(y_test, y_pred))

Accuracy: 0.9985242516626963

Confusion matrix:
 [[   287      0      0      0    102      0      0]
 [     0   1828      0      0      2      0      0]
 [     0      0  25593      2      8      0      0]
 [     0      0      0  38655     92      2      0]
 [    39      0      2     63 418722    184      2]
 [     0      0      0      8    222  17906      3]
 [     0      0      0      1     12      0    416]]

Classification_report:
                 precision    recall  f1-score   support

          Bots       0.88      0.74      0.80       389
   Brute Force       1.00      1.00      1.00      1830
          DDoS       1.00      1.00      1.00     25603
           DoS       1.00      1.00      1.00     38749
Normal Traffic       1.00      1.00      1.00    419012
 Port Scanning       0.99      0.99      0.99     18139
   Web Attacks       0.99      0.97      0.98       429

      accuracy                           1.00    504151
     macro avg       0.98      0.96      0.97    504151

In [8]:
joblib.dump(model, "model_rf.pkl")
print("Success")

Success
